# Generated by Django 5.2.6 on 2025-09-14 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Missingperson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='missing_person/')),
                ('description', models.TextField(blank=True)),
                ('date_repo', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Detectionmodelresult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_file', models.FileField(upload_to='videos/')),
                ('frame_number', models.IntegerField()),
                ('timestamp', models.FloatField()),
                ('confidence_score', models.FloatField()),
                ('detect_at', models.DateTimeField(auto_now_add=True)),
                ('missingperson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='missingpersondetectionapp.missingperson')),
            ],
        ),
    ]
