# Generated by Django 5.2.6 on 2025-09-16 15:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missingpersondetectionapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detectionmodelresult',
            name='confidence_score',
        ),
        migrations.RemoveField(
            model_name='detectionmodelresult',
            name='detect_at',
        ),
        migrations.RemoveField(
            model_name='detectionmodelresult',
            name='frame_number',
        ),
        migrations.RemoveField(
            model_name='detectionmodelresult',
            name='missingperson',
        ),
        migrations.RemoveField(
            model_name='detectionmodelresult',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='detectionmodelresult',
            name='video_file',
        ),
        migrations.AddField(
            model_name='detectionmodelresult',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='detectionmodelresult',
            name='found',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='detectionmodelresult',
            name='frames_detected',
            field=models.TextField(default='[]'),
        ),
        migrations.AddField(
            model_name='detectionmodelresult',
            name='missing_person_name',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='detectionmodelresult',
            name='total_frames',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='detectionmodelresult',
            name='video_filename',
            field=models.CharField(default='unknown_video.mp4', max_length=255),
        ),
    ]
