# Generated by Django 5.2.6 on 2025-09-17 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missingpersondetectionapp', '0002_remove_detectionmodelresult_confidence_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='missingperson',
            name='embedding',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
